Adding Reserve Gift Policy
celo-org/governance pull request #119
Opened 2022-02-01 14:30 UTC by martinvol

2022-02-01 14:39 UTC, sudarics requested changes
Link to discussion:
https://forum.celo.org/t/discussion-for-cgp-48-reserve-gift-policy/2771

2022-02-01 14:49 UTC, martinvol commented on CGPs/CGP-0048.md
> +discussions-to: <link to discussion on forum.celo.org>
```suggestion
discussions-to: https://forum.celo.org/t/discussion-for-cgp-48-reserve-gift-policy/2771
```

2022-02-01 14:55 UTC, sudarics approved these changes

2022-02-01 14:55 UTC, sudarics approved these changes

2022-02-04 20:19 UTC, YazzyYaz approved these changes

2022-02-04 20:19 UTC, merged