Top up liquidity cgp 0065
celo-org/governance pull request #183
Opened 2022-11-24 16:40 UTC by rcroessmann

Proposal to top up the Mento cUSD/USDCet pool on Mobius with 10M USDCet (portal).

2022-11-29 03:01 UTC, willkraft requested changes
Hey Roman, thanks for putting together such a detailed proposal. It looks great, and I just have a minor comment. The header is slightly off - would you mind updating the header to match what's in the [CGP template file](https://github.com/celo-org/governance/blob/main/CGPs/cgp-template.md)?

2022-12-01 08:47 UTC, rcroessmann commented
> Hey Roman, thanks for putting together such a detailed proposal. It looks great, and I just have a minor comment. The header is slightly off - would you mind updating the header to match what's in the [CGP template file](https://github.com/celo-org/governance/blob/main/CGPs/cgp-template.md)?

Thanks for the hint @willkraft, adjusted!

2022-12-01 09:16 UTC, rcroessmann commented
PR good to be merged from my end. Anything missing from your perspective @willkraft?

2022-12-01 15:04 UTC, willkraft approved these changes

2022-12-01 17:59 UTC, calicokittencat approved these changes

2022-12-01 17:59 UTC, merged