Celo Tribe Web3 Social Club
celo-org/governance pull request #192
Opened 2022-12-10 15:49 UTC by Hawwal

---
CGP: 0069
title: Celo Tribe Web3 Social club 
date-created: 10/12/2022
author: Hawwal Ogungbadero @hawwal 
status: DRAFT 
discussions-to: <link to discussion on forum.celo.org>
governance-proposal-id: [if submitted]
date-executed: [if executed] 
---

![celo tribe](https://user-images.githubusercontent.com/98647296/206863413-14eb35b9-4432-4e40-ad6d-c4c07149a9a4.png)

West Africa where I come from is endowed with a lot of brilliant minds and the youth generation is fast evolving.
This lead me to come up with the ‘Tribe’ movement which is “a web3 social club dedicated to inspiring, educating, and exposing youths in higher institutions to the vast opportunities in Web3 building a fully functional community of young minds in Web3.”
Social clubs in higher institutions or universities are not entirely a new thing and some clubs go as far back as the 90s.

Below are a few schools with lists of registered clubs in their schools:
[Nile University](https://www.nileuniversity.edu.ng/clubs-and-activities/)
[UI University of Ibadan](https://www.ui.edu.ng/listofregisteredclubsandsocieties)
[Covenenant university UNESCO](https://covenantuniversity.edu.ng/information/more/covenant-news/407-unesco-youth-club-covenant-chapter-commences-operations)
Each school consists of various departments covering many studies in sciences, education, law, engineering, medicine, and so on. we believe these fields have a role to play in web3 and we want to expose them to Celo.

## Traction:
A few months back we held the first-ever Tribe event and we planted the first club cell which was tagged “Tribe LASUTH 1". Currently, we have about 20 active members in the club all discussing web3 and possible infusion into their field of study which happens to be medicine. check out this blog post on medium.

## Goal:
Our goal is to engage and directly chart the course of these potential young people to a future in web3 and Celo.
In achieving this, we have decided to pioneer this social club community titled: Celo Tribe which we look to establish in universities across West Africa focused on empowering these youths with the right information to harness their skills and groom them to their fullest potential exposing them to Celo and the possibilities of building in Celo.

Our initial target region is West Africa Nigeria and, her total number of universities was estimated at over 170 schools to date with Lagos State estimated to have over 11 universities inclusive of privately-owned schools.

We look to establish Celo Tribe in these schools over the next 5 months duration.

Pan Atlantic University, Lagos State, Nigeria
University of Lagos
Lagos state university
Yaba college of technology
Lagos State Polytechnic
Babcock University
Redeemer’s university
Covenant University
University of Ibadan
University of Benin
Federal Polytechnic of Technology (Akure)
Ahmadu Bello University
University of Ilorin
Ambrose Alli University
American University of Nigeria
Bells University of Technology
Calebs university
Benson Idahosa university
University of Nigeria 1
University of Abuja
Veritas University Abuja
Obafemi Awolowo University
Nile University

## Tribe monthly curriculum Schedule
Seminars:- Seminars will be hosted Bi-monthly where web3 facilitators/enthusiasts from around Africa will be invited to discuss with the students.
School activities:- Bi-weekly meetings will hold as they discuss weekly topics in the course outline presented to the tribal leaders in each school.
Competitions:- These will hold monthly or Bi-monthly depending on their school syllabus and school activities.
Events:- These will be organized monthly by students with catchy themes each month.
Reports:- Reports will be presented by school tribal leaders on a monthly bases for follow-ups and to see better approaches and implementations.

## Celo Tribe Social
We want to take this a huge step further by creating social channels which students can follow and get up-to-date information on tribe activities done in other schools to inspire them about what they could do in their Tribe community. We will be setting up social pages on these platforms:
Twitter
Telegram
Discord (Tribe Channel)
Instagram
Also frequent blog posts on blaqk stereo as well as medium will be implemented

## KPI:
Establishment of Celo Tribe clubs in 23 universities.
completion of at least 15 events and seminars in 5 months duration.
opening of fully operational Celo Tribe social pages.

## Timeline:
| School	| Date	| Season |
|-----------|-------|--------|
| Unilag	| Dec. 2022	| 1st |
| Yabatech	| -	| - |
| Lagos state university	| - | - |
| Lagos state poly	| - | - |
| Pan atlantic Uni	| Jan. 2022	| - |
| Babcock Uni	| -	| - |
| Redeemer’s Uni	| -	| - |
| Covenant University	| Feb 2023	| – |
| University of Ibadan	| -	| - |
| University of Ilorin	| -	| - |
| Obafemi Awolowo University	| -	| - |
| Federal Polytechnic of Technology (Akure)	| - | - |
| Bells University of Technology | Mar 2023	| - |
| Calebs university	| -	| - |
| University of Benin	| -	| - |
| Benson Idahosa university	| - | - |
| University of Nigeria	| -	| - |
| Ambrose Alli University	| April 2023	| - |
| University of Nigeria	| -	| - |
| University of Abuja	| -	| - |
| Veritas University Abuja	| -	| - |
| Nile University	| -	| - |
| American University of Nigeria	| -	| - |

## Team:
Hawwal: Team lead and founder:Blaqk Stereo Dao & Tribe Club - In
Timi: Project Manager - In 
Benny: Community manager - In
Shola: Social media - ln

## Budget:
We request $49,860 for the next five months (December - April 2023 (holiday season excluded) in the execution of this project.

Initial expense:
|Description |	Price ($) |
|-----------|-------------|
| Graphics for banner including Celo tribe logo design | 200 |
| Celo Tribe cover letter magazine for (5 States education boards) |	500 |
| Total	| 700 |
We estimate to spend $1,920 USD in each school and here is a detailed breakdown:

| Description	| Cost ($) |
|---------------|----------|
| Refreshments for each launch event (Food and drinks) |	300 |
| The Tribe Booklet for at least 100 club members ($3 per copy) |	300 |
| Sound for event	| 100 |
| Branded Celo Tribe T-shirts for 5 club officials ($10 per shirt) |	50 |
| Logistics (transportation inter state)	| 400 |
| Banner print 2x ($50 for a banner)	| 100 |
| Esco’s salary is $30 per month (x3 months) for 3 Tribal leaders a school	| 90x3 = 270 |
| Club bi-monthly events $200 (x2)	| 400 |
| Total 1,920 x 23 schools =	| 44,160 |

Socials plan:-
| Description	Duration	| cost ($) |
|---------------------------|----------|
| 2 posts a day(graphics) with 4 motion graphics a week & 2 event videos |	month	| 1000 |
| Total	| 5 months	| 5,000 |

## P.S
Added in this pull is a snippet of the course outline and the 20 topics that will be discussed in the clubs.

Thanks.

2022-12-10 16:26 UTC, Hawwal commented
[Celo Tribe Course outline.pdf](https://github.com/celo-org/governance/files/10200437/Celo.Tribe.Course.outline.pdf)

cc @willkraft @ericnakagawa @calicokittencat

2022-12-16 04:44 UTC, willkraft requested changes
Hi Hawwal, thanks for putting this together. The header doesn't look quite right here (bolded) - would you mind adjusting to match the CGP template? You can see it here: https://github.com/celo-org/governance/blob/main/CGPs/cgp-template.md

2022-12-16 04:46 UTC, willkraft approved these changes
Actually, I was looking at it incorrectly - it looks good.

2022-12-16 19:58 UTC, calicokittencat approved these changes

2022-12-16 20:00 UTC, merged