CGP 85: Add USDC/EUR and USDC/BRL oracles
celo-org/governance pull request #285
Opened 2023-07-13 12:16 UTC by nvtaveras

This CGP draft aims to add USDC/EUR and USDC/BRL oracles which are required for the 2nd phase of the Multi-Collateral Mento upgrade.

2023-07-16 10:55 UTC, juanjgiraldoc requested changes
Can you please upgrade CGP to CGP-0086 _(CGP-0085 already taken by [GoodDollar Gas proposal](https://github.com/celo-org/governance/pull/284))_

2023-07-17 10:47 UTC, nvtaveras commented
> Can you please upgrade CGP to CGP-0086 _(CGP-0085 already taken by [GoodDollar Gas proposal](https://github.com/celo-org/governance/pull/284))_

updated!

2023-07-17 11:04 UTC, juanjgiraldoc approved these changes

2023-07-17 15:22 UTC, 0xzoz approved these changes

2023-07-17 15:22 UTC, merged