Create CGP-0093
celo-org/governance pull request #308
Opened 2023-08-10 18:42 UTC by climateXcrypto

2023-08-10 20:59 UTC, 0xzoz requested changes

2023-08-10 20:59 UTC, 0xzoz commented on CGPs/cgp-0093.md
> +* **Multisign Address:** XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
We will need a multisig set up before we can merge this. The Gnosis safe integration is what most proposers use.

2023-08-10 20:59 UTC, 0xzoz commented on CGPs/cgp-0093/mainnet.json
> +      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
The multisig address must also be added here before merging

2023-08-11 19:16 UTC, 0xzoz commented on CGPs/cgp-0093/mainnet.json
> +      "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
@climateXcrypto thanks for updating the multisig in the readme. Could you please add it to the payload here aswell?

2023-08-11 21:03 UTC, juanjgiraldoc approved these changes

2023-08-11 21:06 UTC, 0xzoz approved these changes

2023-08-11 21:06 UTC, merged