chore: add template md and cgp folder
celo-org/governance pull request #472
Opened 2024-08-26 14:52 UTC by philbow61

# Draft

2024-08-27 16:42 UTC, work-0xj4an requested changes

2024-08-27 16:42 UTC, work-0xj4an commented on CGPs/cgp-0146.md
> +date-executed: TBD
Please leave this fields empty otherwise Rosy's validation tool is not gonna pass.

2024-08-27 19:08 UTC, work-0xj4an approved these changes

2024-08-28 15:06 UTC, 0xGoldo approved these changes

2024-08-28 15:06 UTC, merged