[NOT READY FOR REVIEW] Artemis Sept Proposal
celo-org/governance pull request #481
Opened 2024-09-10 20:19 UTC by anthonyyim

2024-09-13 18:07 UTC, work-0xj4an requested changes

2024-09-13 18:07 UTC, work-0xj4an commented on CGPs/cgp-0148.md
> +status: PROPOSED
Please change this to "DRAFT"

2024-09-19 03:44 UTC, work-0xj4an approved these changes

2024-09-19 07:26 UTC, 0xGoldo approved these changes

2024-09-19 07:26 UTC, merged