CGP-0042 - cBRL contract deploy
celo-org/governance pull request #77
Opened 2021-10-09 23:24 UTC by luisgj

- init setup WIP-
- Adds DRAFT for cBRL CGP part 1

2021-10-12 10:09 UTC, martinvol commented on CGPs/cgp-0042.md
> +- Author(s): @luisgj @volpe
```suggestion
- Author(s): @luisgj @martinvol
```

2021-10-12 10:10 UTC, martinvol approved these changes

2021-10-12 15:23 UTC, YazzyYaz commented on CGPs/cgp-0042.md
> +# CGP [0042]: cBRL contract deploy
please follow the new template preamble here: https://github.com/celo-org/governance/blob/main/CGPs/cgp-template.md

2021-10-12 15:24 UTC, YazzyYaz requested changes

2021-10-12 15:24 UTC, YazzyYaz commented on CGPs/cgp-0042.md
> +- DRAFT = Feedback collection
Can delete this subsection

2021-10-12 15:24 UTC, YazzyYaz commented on CGPs/cgp-0042.md
> +TODO - Gather Feedback on Proposed changes
Gathering feedback should be done outside the specifications of the governance proposal.

2021-10-12 15:24 UTC, YazzyYaz commented on CGPs/cgp-0042.md
> +5. *TDB: Oracle setting, freezing the contracts, setting constitution parameters.*
add space after section 5.

2021-10-13 18:37 UTC, calicokittencat approved these changes

2021-10-13 20:06 UTC, merged

2021-10-13 21:22 UTC, luisgj commented
sorry mates. I was too slow to see the comments. Thanks for merging.